// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qejaocvosshndqbstysn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlamFvY3Zvc3NobmRxYnN0eXNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mzk0NDYsImV4cCI6MjA2NTUxNTQ0Nn0.JE6uDzV5aHdV0gDQY6T_1YBpfiwm6M11vPFW5Dao5e4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);